### ISSUE TITLE
TypeError: Cannot read property '__expression' of undefined

### ISSUE THREAD

**Issue by michaelhthomas** [windicss/gridsome-plugin-windicss#11]
After installing this plugin, chain webpack throws this error, along with an equally unhelpful stack trace.

```
TypeError: Cannot read property '__expression' of undefined
    at Object.toConfig (./node_modules/webpack-chain/src/Plugin.js:56:38)
    at ./node_modules/webpack-chain/src/Config.js:131:61
    at Array.map (<anonymous>)
    at module.exports.toConfig (./node_modules/webpack-chain/src/Config.js:131:40)
    at Compiler.resolveWebpackConfig (./node_modules/gridsome/lib/app/Compiler.js:53:38)
    at createWebpackConfig (./node_modules/gridsome/lib/develop.js:132:25)
    at async module.exports ./node_modules/gridsome/lib/develop.js:28:25)
```

Any ideas on what's causing this and how to fix it?

## Steps to Replicate

- Create new gridsome site
- Install `gridsome-plugin-windicss`
- Add plugin to configuration
- Attempt to start dev server

**Comment by michaelhthomas** [comment]
It looks like this change fixes it:

```diff
# Line 29
-const WebpackWindiCSSPlugin = require('windicss-webpack-plugin').default
+const WebpackWindiCSSPlugin = require('windicss-webpack-plugin')
```

Probably related to [this change](https://github.com/windicss/windicss-webpack-plugin/releases/tag/1.5.0) in the webpack plugin.

**Comment by rylanharper** [comment]
@harlan-zw Any chance on getting this plugin getting updated by the authors? @michaelhthomas that is indeed the fix for this. Thanks!:)

**Comment by harlan-zw** [comment]
Hey @michaelhthomas and @rylanharper 

Apologies for the delay and thanks for the ping. Release 1.0.5 should have the issue sorted, let me know if you have any issues :)
