### ISSUE TITLE
max-width classes not working

### ISSUE THREAD

**Issue by deeplinked** [windicss/gridsome-plugin-windicss#2]
installed windicss plugin on a fresh install of gridsome. i am trying to set max-width of the page layout `container mx-auto max-w-screen-lg` not working. but width classes are working, if i use `w-lg` instead of `max-w-screen-lg` or `max-w-lg` its working.

**Comment by harlan-zw** [comment]
Hey @deeplinked 

Thanks for the issue. I don't think you should use container with max-screen-lg? Seems like the container takes priority
